### ISSUE TITLE
Default Exported Classes Are Ignored

### ISSUE THREAD

**Issue by theovier** [achlubek/aero-di#5]
Hi,

I'm unsure if the observed behaviour is expected or not. I noticed that classes which are exported by the `export default` statement don't show up in the generated reflection file. Consider this:

```ts
// foobar.ts
export class Foo {} // ✅  shows up in the generated reflection file 
```

```ts
// foobar.ts
class Foo {} // ✅ does not show up in the generated reflection file (reasonable, it's not exported, and, thus not usable)  
```

```ts
// foobar.ts
class Foo {} // ❌ does not show up in the generated reflection file 

export default Foo
```

The verbose output for the last example is: 

```
Generating reflection to reflection.generated.ts for directory ...
Analyzing file foobar.ts
Saved data for 0 classes
Saved data for 0 interfaces
```

Is this intended?

Kind regards,
Theo

**Comment by achlubek** [comment]
Hi, definitely looks like not intended, I don't think I covered this path, I think `export default class Foo` would also not play well. Thanks for this, I will work on that but this one will take a bit more time than last one 😁

**Comment by achlubek** [comment]
Work is in progress in the pull request, turns out it wasn't that difficult to implement. I will test it for some time and release later today.

**Comment by theovier** [comment]
Can confirm, it now generates the reflection data for default exported classes. Thanks! 🚀
